import { Motorcycle } from './motorcycle';

export const MOTORCYCLES: Motorcycle[] = [
    {
        id: 1,
        link:"https://www.leboncoin.fr/motos/1501395425.htm/",
        model: 'R 1200 GS lc',
        is_gsa: false,
        color: "black",
        year: 2013,
        kilometer: 24000,
        price: 12400,
        dynamic_pack: true,
        touring_pack: true,
        comfort_pack: true,    
        has_side_cases: true,
        has_top_case: false,
        bmw_luggages: true,
        aluminium_luggages: false,
        estimated_price: 0
    },
    {
        id: 2,
        link:"https://www.leboncoin.fr/motos/1475709906.htm/",
        model: 'R 1200 GS lc',
        is_gsa: false,
        color: "black",
        year: 2016,
        kilometer: 14900,
        price: 15700,
        dynamic_pack: true,
        touring_pack: true,
        comfort_pack: true,    
        has_side_cases: false,
        has_top_case: true,
        bmw_luggages: true,
        aluminium_luggages: false,
        estimated_price: 0   
    },
    {
        id: 3,
        link:"https://www.leboncoin.fr/motos/1500475450.htm/",
        model: 'R 1200 GS lc',
        is_gsa: false,
        color: "white",
        year: 2014,
        kilometer: 53000,
        price: 12000,
        dynamic_pack: true,
        touring_pack: true,
        comfort_pack: true,    
        has_side_cases: true,
        has_top_case: true,
        bmw_luggages: true,
        aluminium_luggages: false,
        estimated_price: 0   
    },
    {
        id: 4,
        link:"https://www.leboncoin.fr/motos/1498951934.htm/",
        model: 'R 1200 GS lc',
        is_gsa: true,
        color: "white",
        year: 2015,
        kilometer: 16000,
        price: 14500,
        dynamic_pack: true,
        touring_pack: true,
        comfort_pack: true,    
        has_side_cases: false,
        has_top_case: true,
        bmw_luggages: true,
        aluminium_luggages: true,
        estimated_price: 0   
    },
    {
        id: 5,
        link:"https://www.leboncoin.fr/motos/1498644170.htm/",
        model: 'R 1200 GS lc',
        is_gsa: false,
        color: "white",
        year: 2014,
        kilometer: 28000,
        price: 13000,
        dynamic_pack: true,
        touring_pack: true,
        comfort_pack: true,    
        has_side_cases: false,
        has_top_case: true,
        bmw_luggages: false,
        aluminium_luggages: false,
        estimated_price: 0   
    },
    {
        id: 6,
        link:"https://www.leboncoin.fr/motos/1495421937.htm/",
        model: 'R 1200 GS lc',
        is_gsa: true,
        color: "green",
        year: 2014,
        kilometer: 58200,
        price: 12990,
        dynamic_pack: true,
        touring_pack: true,
        comfort_pack: true,    
        has_side_cases: true,
        has_top_case: true,
        bmw_luggages: true,
        aluminium_luggages: true,
        estimated_price: 0   
    },
    {
        id: 6,
        link:"https://www.leboncoin.fr/motos/1491644260.htm/",
        model: 'R 1200 GS lc',
        is_gsa: false,
        color: "black",
        year: 2013,
        kilometer: 23800,
        price: 12800,
        dynamic_pack: true,
        touring_pack: true,
        comfort_pack: true,    
        has_side_cases: true,
        has_top_case: true,
        bmw_luggages: true,
        aluminium_luggages: true,
        estimated_price: 0   
    }    
];
